### ISSUE TITLE
 The SessionStateTempDataProvider class requires session state to be enabled : Error on production server

### ISSUE THREAD

**Issue by mohsen-d** [brockallen/CookieTempData#12]
I'm using the library on Dev server and it works but when I upload it to the production server , It throws an exception as below : 

The SessionStateTempDataProvider class requires session state to be enabled.

System.InvalidOperationException: The SessionStateTempDataProvider class requires session state to be enabled.

   at System.Web.Mvc.SessionStateTempDataProvider.SaveTempData(ControllerContext controllerContext, IDictionary`2 values)

   at System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult)

   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)

   at System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState)

   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)

   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()

   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

I'm using StructureMap by the way.

**Comment by brockallen** [comment]
This is an MVC error and unrelated to the CookieTempDataProvider -- look at the call stack.
